### ISSUE TITLE
Provided example doesn't work out of the box

### ISSUE THREAD

**Issue by jetztgradnet** [diffplug/goomph#1]
Hi,

I tried the example from the Readme, but it didn't work with Gradle 2.14: it couldn't find the plugin:

```
A problem occurred evaluating root project 'gradle-goomph'.
> Plugin with id 'com.diffplug.gradle.oomph.ide' not found.
```

Is there some additional dependency or buildscript necessary to be able to load the plugin?

Steps to reproduce:
1. create empty folder
2. create build.gradle with example from README.md
3. run gradle

```bash
myuser [~/dev/workspaces/gradle-goomph]> gradle -version

------------------------------------------------------------
Gradle 2.14
------------------------------------------------------------

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Mac OS X 10.11.5 x86_64

myuser [~/dev/workspaces/gradle-goomph]> vi build.gradle
myuser [~/dev/workspaces/gradle-goomph]> cat build.gradle 
apply plugin: 'com.diffplug.gradle.oomph.ide'
oomphIde {
    p2.addRepoEclipse('4.6.0')             // 4.6.0 neon has lots of new features
    p2.addIU("org.eclipse.platform.ide");  // we want the Eclipse IDE
    p2.addFeature("org.eclipse.jdt");      // with the Java development tools

    eclipseIni {
        vmargs('-Xmx2g')    // IDE can have up to 2 gigs of RAM
    }

    classicTheme()  // oldschool cool
    niceText()      // with nice fonts and visible whitespace
}
myuser [~/dev/workspaces/gradle-goomph]> 
myuser [~/dev/workspaces/gradle-goomph]> 
myuser [~/dev/workspaces/gradle-goomph]> gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/myuser/dev/workspaces/gradle-goomph/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'gradle-goomph'.
> Plugin with id 'com.diffplug.gradle.oomph.ide' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.883 secs
myuser [~/dev/workspaces/gradle-goomph]> 
```

**Comment by nedtwigg** [comment]
Hi there!  Sorry, two problems.  First problem is that you need to add the snapshot repository:  Second problem is we acted on some suggestions and didn't update the README yet.  I just fixed both in the README.

The following will work:

```
buildscript {
	repositories {
		// we're iterating with our early adopters on a snapshot right now
		maven {	url 'https://oss.sonatype.org/content/repositories/snapshots/' }
	}
	// make sure we don't cache stale snapshot versions
	configurations.all {
		resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
	}
	dependencies {
		classpath "com.diffplug.gradle:goomph:3.0.0-SNAPSHOT"
	}
}

apply plugin: 'com.diffplug.gradle.oomph.ide'
oomphIde {
	jdt {}
	eclipseIni {
		vmargs('-Xmx2g')    // IDE can have up to 2 gigs of RAM
	}
	style {
		classicTheme()  // oldschool cool
		niceText()      // with nice fonts and visible whitespace
	}
}
```

I think the [javadoc](https://diffplug.github.io/goomph/javadoc/snapshot/com/diffplug/gradle/oomph/OomphIdePlugin.html) will be helpful too :)

**Comment by johndevs** [comment]
Looks like the example isn't creating the right folders/files. Get this when I try to run it:

```
john@xps ~/R/designerProduct [1]> gradle -s ide
:ideSetupP2
Installing org.eclipse.platform.ide 4.6.0.I20160606-1100.
Installing org.eclipse.jdt.feature.group 3.12.0.v20160606-1100.
Installing org.eclipse.ui.views.log 1.2.0.v20160418-1724.
Operation completed in 6981 ms.
:ideSetupP2 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ideSetupP2'.
> java.io.FileNotFoundException: /home/john/Repositories/designerProduct/build/oomph-ide/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info (No such file or directory)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ideSetupP2'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: com.diffplug.common.base.Errors$WrappedAsRuntimeException: java.io.FileNotFoundException: /home/john/Repositories/designerProduct/build/oomph-ide/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info (No such file or directory)
	at com.diffplug.common.base.Errors.asRuntime(Errors.java:408)
	at com.diffplug.common.base.Errors.rethrowErrorAndWrapOthersAsRuntime(Errors.java:132)
	at com.diffplug.common.base.Errors$Rethrowing.lambda$new$10(Errors.java:327)
	at com.diffplug.common.base.Errors.lambda$wrap$5(Errors.java:220)
	at com.diffplug.common.base.Errors.run(Errors.java:210)
	at com.diffplug.gradle.oomph.OomphIdePlugin.lambda$applyOnce$89(OomphIdePlugin.java:133)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
Caused by: java.io.FileNotFoundException: /home/john/Repositories/designerProduct/build/oomph-ide/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info (No such file or directory)
	at com.diffplug.common.io.Files$FileByteSource.openStream(Files.java:126)
	at com.diffplug.common.io.Files$FileByteSource.read(Files.java:150)
	at com.diffplug.common.io.Files.toByteArray(Files.java:260)
	at com.diffplug.gradle.FileMisc.modifyFile(FileMisc.java:219)
	at com.diffplug.gradle.oomph.OomphIdeExtension.writeBrandingPlugin(OomphIdeExtension.java:273)
	at com.diffplug.gradle.oomph.OomphIdeExtension.ideSetupP2(OomphIdeExtension.java:237)
	at com.diffplug.common.base.Errors.lambda$wrap$5(Errors.java:218)
	... 63 more
```

**Comment by nedtwigg** [comment]
1. What OS are you using?
2. Are there any files in `build/oomph-ide/configuration/`?

Btw, snapshot has changed again, final API will release this weekend.  Needs to add `repoEclispeLatest()` line.

```
apply plugin: 'com.diffplug.gradle.oomph.ide'
oomphIde {
    repoEclipseLatest()
    jdt {}
    eclipseIni {
        vmargs('-Xmx2g')    // IDE can have up to 2 gigs of RAM
    }
    style {
        classicTheme()  // oldschool cool
        niceText()      // with nice fonts and visible whitespace
    }
}
```

**Comment by nedtwigg** [comment]
I've tested the current examples and releases on win/mac/linux.  If you still have problems, feel free to reopen!
