### ISSUE TITLE
Product build fails due to missing plugin

### ISSUE THREAD

**Issue by thomasmhofmann** [diffplug/goomph#10]
Hi,
when I try to build a product with PdeBuildTask I get:

```
Caused by: java.lang.IllegalArgumentException: No such plugin: org.eclipse.update.configurator
        at com.diffplug.gradle.pde.ExplicitVersionPolicy.useVersions(ExplicitVersionPolicy.java:97)
        at com.diffplug.gradle.pde.PluginCatalog.getVersionsFor(PluginCatalog.java:125)
        at com.diffplug.gradle.pde.ProductFileUtil.transformProductFile(ProductFileUtil.java:69)
        at com.diffplug.gradle.pde.PdeProductBuildConfig.lambda$transformProductFile$129(PdeProductBuildConfig.java:118)
        at com.diffplug.common.base.StringPrinter.buildString(StringPrinter.java:73)
        at com.diffplug.gradle.pde.PdeProductBuildConfig.transformProductFile(PdeProductBuildConfig.java:115)
        at com.diffplug.gradle.pde.PdeProductBuildConfig.setup(PdeProductBuildConfig.java:93)
        at com.diffplug.gradle.pde.PdeBuildTask.build(PdeBuildTask.java:172)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

My target platform that I use to build the RCP Product does not include that plugin. So I mirrored the eclipse in addition like this:

```
import com.diffplug.gradle.pde.EclipseRelease

apply plugin: 'com.diffplug.gradle.p2.asmaven'

p2AsMaven {
    //destination buildDir
    group 'eclipse-deps', {
        repoEclipse '4.5.2'
        feature 'org.eclipse.equinox.executable'
        feature 'org.eclipse.rcp.configuration'
        feature 'org.eclipse.platform'
        repo2runnable()
    }
    group 'eip-target', {
        repo 'file:/C:/target-platforms/eip'
        feature 'de.justiz.eip.e4.platform.feature'
        repo2runnable()
    }
}

```

Now I have p2 repos for my target platform and for the eclipse release like shown above.
Now I am unclear on where the PdeBuildTask is looking for the plugin. I figured that the base would need to be set to eclipse-deps and addPluginPath would need to contain the plugins for my product. This does not help though.

Can you please provide some details on how PdeBuildTask to build a p2 repo tries to resolve the plugins needed to run the director app and then on the other hand where I need to put my bundles for the app to build?

Thank you.

**Comment by nedtwigg** [comment]
Take a look at the gradle and eclipse RCP example's [usage of PdeBuildTask](https://github.com/diffplug/gradle_and_eclipse_rcp/blob/master/deploy/build.gradle).

There isn't any automatic wiring between the PdeBuildTask and p2asmaven - you've got to use `addPluginPath()` and `base()` to set the lookup paths.

**Comment by thomasmhofmann** [comment]
Yes sure, but what is the base path and where does it look for the org.eclipse.update.configurator plugin (which is not needed in my target platform)?

**Comment by nedtwigg** [comment]
I believe that "base" is the eclipse installation that you're building against.  In your case, I think you should have:

```
task buildP2(type: PdeBuildTask) {
    base(rootProject.file('target.p2/build/p2asmaven/p2runnable/eclipse-deps'))
    addPluginPath(rootProject.file('target.p2/build/p2asmaven/p2runnable/eclipse-deps'))
    addPluginPath(rootProject.file('target.p2/build/p2asmaven/p2runnable/eip-target'))
...
```

**Comment by nedtwigg** [comment]
Closing due to inactivity, feel free to reopen.
