### ISSUE TITLE
p2AsMaven causes NullPointerException when looking for ANT tools

### ISSUE THREAD

**Issue by fvgh** [diffplug/goomph#144]
The problem occurs since release `3.28.0`. With `3.27.0` p2AsMaven works charmingly.
The problem can be observed in [Spotless CI](https://app.circleci.com/pipelines/github/diffplug/spotless/963/workflows/1e9c2a4d-35e8-44dc-800a-18a2c6f02289/jobs/5425).

> Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.diffplug.gradle.eclipserunner.JarFolderRunner.run(JarFolderRunner.java:51)
	at com.diffplug.gradle.eclipserunner.JarFolderRunnerExternalJvm$RunOutside.run(JarFolderRunnerExternalJvm.java:126)
	at com.diffplug.gradle.JavaExecable.main(JavaExecable.java:134)
Caused by: java.lang.NullPointerException
	at org.eclipse.ant.core.AntCorePreferences.findHighestAntVersion(AntCorePreferences.java:562)
	at org.eclipse.ant.core.AntCorePreferences.getDefaultAntHomeEntries(AntCorePreferences.java:507)
...

**Comment by nedtwigg** [comment]
Linking to sourcecode stacktrace.

- https://github.com/eclipse/eclipse.platform/blob/9bb393cb56c049c7eeacd61fb859743c52c7b6a3/ant/org.eclipse.ant.core/src/org/eclipse/ant/core/AntCorePreferences.java#L562
- https://github.com/eclipse/eclipse.platform/blob/9bb393cb56c049c7eeacd61fb859743c52c7b6a3/ant/org.eclipse.ant.core/src/org/eclipse/ant/core/AntCorePreferences.java#L507

I've tried a few things, but none have worked so far.
