### ISSUE TITLE
EclipseMavenCentral incompatible with configuration cache on macOS

### ISSUE THREAD

**Issue by liblit** [diffplug/goomph#203]
When trying to build a project that uses the `EclipseMavenCentral` plugin, if the Gradle configuration cache is enabled, then diagnostic messages report an incompatibility between the plugin and the cache:

```
* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Build file 'build.gradle.kts': external process started 'uname -a'
  See https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:external_processes
```

The full configuration cache report as additional, useful details:

```
org.gradle.api.InvalidUserCodeException: Starting an external process 'uname -a' during configuration time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onExternalProcessStarted(ConfigurationCacheProblemsListener.kt:84)
	at org.gradle.configurationcache.InstrumentedInputAccessListener.externalProcessStarted(InstrumentedInputAccessListener.kt:110)
	at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:394)
	at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:398)
	at org.gradle.internal.classpath.Instrumented.exec(Instrumented.java:259)
	at com.diffplug.common.swt.os.OS.exec(OS.java:156)
	at com.diffplug.common.swt.os.OS.calculateNative(OS.java:133)
	at com.diffplug.common.swt.os.OS.detectPlatform(OS.java:113)
	at com.diffplug.common.swt.os.OS.detectPlatform(OS.java:120)
	at com.diffplug.common.swt.os.OS.getNative(OS.java:100)
	at com.diffplug.gradle.FileMisc.<clinit>(FileMisc.java:426)
	at com.diffplug.gradle.eclipse.MavenCentralMapping.createVersionMap(MavenCentralMapping.java:138)
	at com.diffplug.gradle.eclipse.MavenCentralMapping.groupIdArtifactIdToVersion(MavenCentralMapping.java:124)
	at com.diffplug.gradle.eclipse.MavenCentralExtension$ReleaseConfigurer.<init>(MavenCentralExtension.java:56)
	at com.diffplug.gradle.eclipse.MavenCentralExtension.release(MavenCentralExtension.java:47)
	at com.diffplug.gradle.eclipse.MavenCentralExtension.release(MavenCentralExtension.java:43)
```

This problem is seen when building on macOS, but not when building on Linux. That clue, plus the "`com.diffplug.common.swt.os.OS.calculateNative(OS.java:133)`" line from the stack trace, lead me to suspect [this macOS-specific code](https://github.com/diffplug/durian-swt/blob/385d94a79949dff5ce4f76c46f10256da9aedd84/durian-swt.os/src/main/java/com/diffplug/common/swt/os/OS.java#L132-L133):

```java
if (isMac) {
	return exec("uname", "-a").contains("_ARM64_") ? MAC_silicon : MAC_x64;
```

That code is from a different GitHub repository: `diffplug/durian-swt`, not `diffplug/goomph`. The relationship between these two repositories is not clear to me, and in any case, my project is not using `diffplug/durian-swt` directly: rater, that code is presumably brought in as a dependency of the `com.diffplug.eclipse.mavencentral` plugin, which I am using directly at version 3.40.0. So I thought it best to report this as an `EclipseMavenCentral` bug, and let the `EclipseMavenCentral` maintainers decide whether and how to report this further upstream as a `diffplug/durian-swt` issue.

If I am right that the problem is running an external `uname -a` process at an inopportune time, note that [the Gradle configuration cache documentation has some useful suggestions for exactly this sort of thing](https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:external_processes).

See also wala/WALA#1230 for the original bug report in a project that uses the `EclipseMavenCentral` plugin. To reproduce this bug, check out [that WALA repository's `master` branch](https://github.com/wala/WALA) on macOS, then run `./gradlew --configuration-cache compileTestJava`.

**Comment by nedtwigg** [comment]
Goomph has a plugin to fix this, it is `com.diffplug.configuration-cache-for-platform-specific-build`, which you must apply in your `settings.gradle` ([link](https://javadoc.io/doc/com.diffplug.gradle/goomph/latest/com/diffplug/gradle/swt/PlatformSpecificBuildPlugin.html)). I thought this wasn't necessary in Gradle 7.6 anymore, but I guess I was wrong... Let me know if this fixes it for you.

**Comment by liblit** [comment]
> Goomph has a plugin to fix this, it is `com.diffplug.configuration-cache-for-platform-specific-build`

Well, that's remarkably specific. 😀

> Let me know if this fixes it for you.

It does. Getting it working required [more changes to my build than just adding a settings plugin](https://github.com/wala/WALA/pull/1231), but once I got the rest figured out, it did indeed fix the problem. Thank you, @nedtwigg!
