### ISSUE TITLE
PdeBuildTask failure

### ISSUE THREAD

**Issue by Tobbe0430** [diffplug/goomph#68]
I've been trying to build an Eclipse RCP application with the help of your plugin and I'm encountering the following error when I'm trying to execute a task of type PdeBuildTask:

> aQute.lib.filter.Filter.matchMap(Ljava/util/Map;)Z

It seems like there might be some issue with plugins containing the Eclipse-PlatformFilter header in the manifest file. However, I don't have any other pluginPath containing a plugin with such a header and the example project builds just fine with the same p2runnable base, so I'm not that sure.

Do you have an idea of why I'm getting that fairly strange error line?

**Comment by nedtwigg** [comment]
Add `--stacktrace` to your gradle command, and copy-paste the output here.

**Comment by Tobbe0430** [comment]
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildProduct'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchMethodError: aQute.lib.filter.Filter.matchMap(Ljava/util/Map;)Z
        at com.diffplug.gradle.pde.PluginCatalog.lambda$addManifest$5(PluginCatalog.java:106)
        at com.diffplug.gradle.pde.PluginCatalog$$Lambda$54/164889760.test(Unknown Source)
        at com.diffplug.common.base.Errors$Rethrowing.lambda$wrapPredicate$13(Errors.java:388)
        at com.diffplug.common.base.Errors$Rethrowing$$Lambda$55/1344590979.test(Unknown Source)
        at com.diffplug.gradle.pde.PluginCatalog.addManifest(PluginCatalog.java:106)
        at com.diffplug.gradle.pde.PluginCatalog.lambda$null$1(PluginCatalog.java:78)
        at com.diffplug.gradle.pde.PluginCatalog$$Lambda$53/1131446986.accept(Unknown Source)
        at com.diffplug.gradle.ZipMisc.read(ZipMisc.java:59)
        at com.diffplug.gradle.pde.PluginCatalog.lambda$new$2(PluginCatalog.java:78)
        at com.diffplug.gradle.pde.PluginCatalog$$Lambda$49/1907616211.accept(Unknown Source)
        at com.diffplug.common.base.Errors.lambda$wrap$6(Errors.java:230)
        at com.diffplug.common.base.Errors$$Lambda$50/13458701.accept(Unknown Source)
        at com.diffplug.gradle.pde.PluginCatalog.<init>(PluginCatalog.java:77)
        at com.diffplug.gradle.pde.PdeProductBuildConfig.setup(PdeProductBuildConfig.java:81)
        at com.diffplug.gradle.pde.PdeBuildTask.build(PdeBuildTask.java:185)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
`

**Comment by nedtwigg** [comment]
- Your build complains that `java.lang.NoSuchMethodError: aQute.lib.filter.Filter.matchMap(Ljava/util/Map;)Z`.
- Goomph is built against bndlib `3.5.0`: https://github.com/diffplug/goomph/blob/7bd69127fc5e5311f7b96d6ffe4cd9a11f0233c8/gradle.properties#L22-L23
- Bndlib 3.5.0 does indeed have the `aQute.lib.filter.Filter.matchMap(Ljava/util/Map;)Z` method: https://github.com/bndtools/bnd/blob/bb70d103dd9c02096f516a0581be0fe9c252d581/aQute.libg/src/aQute/lib/filter/Filter.java#L316
- Bndlib 4.0 has it too, but some of the 2.x releases do not: https://github.com/bndtools/bnd/blob/2.1.0.REL/aQute.libg/src/aQute/lib/filter/Filter.java

So it appears that you're using another plugin in your build which is forcing bndlib to downgrade to 2.x, which means that some of the methods that Goomph needs are missing.

**Comment by Tobbe0430** [comment]
Thank you for your help! This was solved by adding the required version of bndlib since it was hard to determine what plugin was actually causing the downgrade.
